#!/bin/sh

touch /etc/crontabs/root

uci set luci.main.lang=zh_cn
#设置默认主题
#uci set luci.main.mediaurlbase=/luci-static/argon
uci commit luci
	
uci -q set dropbear.@dropbear[0].Interface='lan'
uci commit dropbear
uci set system.@system[0].timezone='CST-8'
uci set system.@system[0].zonename='Asia/Shanghai'
uci -q del system.ntp.server
uci -q add_list system.ntp.server='ntp.tencent.com'
uci -q add_list system.ntp.server='ntp1.aliyun.com'
uci -q add_list system.ntp.server='ntp.ntsc.ac.cn'
uci -q add_list system.ntp.server='cn.ntp.org.cn'
uci commit system

uci -q set uhttpd.main.rfc1918_filter=0
uci -q set uhttpd.main.redirect_https=0
uci -q set uhttpd.main.script_timeout='120'
uci commit uhttpd
uci set fstab.@global[0].anon_mount=1
uci commit fstab

uci -q set upnpd.config.enabled='1'
uci commit upnpd
	
grep -q log-facility /etc/dnsmasq.conf ||
	echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

kernel_version="$(echo -n $(uname -r))"
if [[ -f /lib/modules/$kernel_version/xt_FULLCONENAT.ko || -f /lib/modules/$kernel_version/nft_fullcone.ko ]]; then
	uci -q set firewall.@defaults[0].fullcone='1'
uci commit firewall
fi

ln -sf /sbin/ip /usr/bin/ip

sed -i '/Lienol/d' /etc/opkg/distfeeds.conf
sed -i '/other/d' /etc/opkg/distfeeds.conf
#sed -i 's/downloads.openwrt.org/openwrt.proxy.ustclug.org/g' /etc/opkg/distfeeds.conf
#sed -i 's/http/https/g' /etc/opkg/distfeeds.conf
sed -i "s/# //g" /etc/opkg/distfeeds.conf

#sed -i 's/root::0:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow
 
 uci -q set network.@globals[0].packet_steering=1
 uci commit network
  
uci -q set dhcp.@dnsmasq[0].dns_redirect='0'
uci -q set dhcp.@dnsmasq[0].allservers='1'
uci -q del dhcp.@dnsmasq[0].noresolv
uci -q set dhcp.@dnsmasq[0].cachesize='1500'
uci -q set dhcp.@dnsmasq[0].min_ttl='3600'
uci -q set dhcp.lan.force='1'
uci -q set dhcp.lan.ra='hybrid'
uci -q set dhcp.lan.ndp='hybrid'
uci -q set dhcp.lan.dhcpv6='hybrid'
uci -q set dhcp.lan.force='1'
uci commit dhcp

uci -q set nft-qos.default.limit_enable='0'
uci commit nft-qos

uci -q set system.@system[0].conloglevel='4'
uci -q set system.@system[0].cronloglevel='8'
uci commit system

#uci set network.lan.ipaddr='192.168.119.254'
#uci set network.lan.netmask='255.255.255.0'
uci set network.lan.ip6assign='64'
uci commit network

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
wifi up

sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT'" >> /etc/openwrt_release

# 删除状态页不需显示的
rm -rf /usr/lib/lua/luci/view/admin_status/index
#mv -f /usr/lib/lua/luci/view/admin_status/index /usr/lib/lua/luci/view/admin_status/index_backup 2>/dev/null

sed -i 's#openwrt/luci#lienol/openwrt-luci#g' /usr/lib/lua/luci/view/themes/*/footer.htm

#禁用某些可能会自启动且用不上的依赖包服务
/etc/init.d/php7-fastcgi disable 2>/dev/null
/etc/init.d/php7-fpm disable 2>/dev/null
/etc/init.d/php8-fastcgi disable 2>/dev/null
/etc/init.d/php8-fpm disable 2>/dev/null
/etc/init.d/softethervpnbridge disable 2>/dev/null
/etc/init.d/softethervpnserver disable 2>/dev/null
/etc/init.d/softethervpnclient disable 2>/dev/null
/etc/init.d/haproxy disable 2>/dev/null
/etc/init.d/kcptun disable 2>/dev/null

chmod 0755 /etc/init.d/*

rm -rf /tmp/luci-*cache

exit 0
